// automatically generated by the FlatBuffers compiler, do not modify

package com.alibaba.robot.business.yunqi.bigscreen;

public final class RobotType {
  private RobotType() { }
  public static final byte Robot = 1;
  public static final byte Arm = 2;

  public static final String[] names = { "Robot", "Arm", };

  public static String name(int e) { return names[e - Robot]; }
}

